// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtajZVIzbj6hPmHI75FQnpLV2AoAkDVIA',
    appId: '1:257951661233:android:d2224f58389ceacc407690',
    messagingSenderId: '257951661233',
    projectId: 'digitallami1',
    databaseURL: 'https://digitallami1-default-rtdb.firebaseio.com',
    storageBucket: 'digitallami1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA27QMOyAiHwWdPuulIb3zpw9h-tJV2ks',
    appId: '1:257951661233:ios:f9616517fc11b209407690',
    messagingSenderId: '257951661233',
    projectId: 'digitallami1',
    databaseURL: 'https://digitallami1-default-rtdb.firebaseio.com',
    storageBucket: 'digitallami1.firebasestorage.app',
    iosClientId: '257951661233-tvlkpb5g89j3grbl9n2ocu1refuffvij.apps.googleusercontent.com',
    iosBundleId: 'com.digitallami.appz',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtajZVIzbj6hPmHI75FQnpLV2AoAkDVIA',
    appId: '1:257951661233:web:d2224f58389ceacc407690',
    messagingSenderId: '257951661233',
    projectId: 'digitallami1',
    databaseURL: 'https://digitallami1-default-rtdb.firebaseio.com',
    storageBucket: 'digitallami1.firebasestorage.app',
    authDomain: 'digitallami1.firebaseapp.com',
  );

}