import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:ms2026/Auth/Screen/signupscreen10.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../../service/updatepage.dart';



// Data Models
class Country {
  final String id;
  final String name;

  Country({required this.id, required this.name});
}

class StateModel {
  final int id;
  final String name;
  final String countryId;

  StateModel({required this.id, required this.name, required this.countryId});
}

class City {
  final int id;
  final String name;
  final int stateId;

  City({required this.id, required this.name, required this.stateId});
}

class PartnerPreferencesPagee extends StatefulWidget {
  const PartnerPreferencesPagee({super.key});

  @override
  State<PartnerPreferencesPagee> createState() => _PartnerPreferencesPageeState();
}

class _PartnerPreferencesPageeState extends State<PartnerPreferencesPagee> {
  bool submitted = false;
  bool isLoading = false;

  // Age Range
  double _minAge = 22.0;
  double _maxAge = 60.0;

  // Height Range
  double _minHeight = 121.0;
  double _maxHeight = 215.0;

  // Basic Preferences
  List<String> _selectedMaritalStatus = [];
  String? _selectedProfileWithChildren;
  List<String> _selectedFamilyType = [];

  // Community Details
  List<String> _selectedReligion = [];
  List<String> _selectedCast = [];
  List<String> _selectedsubCast = [];
  List<String> _selectedMotherTongue = [];

  // Astrological Details
  String? _selectedHoroscopeBelief;
  String? _selectedManglik;

  // Location Details - Loaded from API
  List<Country> _countries = [];
  List<StateModel> _allStates = [];
  List<City> _allCities = [];
  List<String> _selectedCountry = [];
  List<String> _selectedState = [];
  List<String> _selectedCity = [];

  // Education Details
  List<String> _selectedQualification = [];
  List<String> _selectedEducationMedium = [];

  // Profession Details
  List<String> _selectedProfession = [];
  List<String> _selectedWorkingWith = [];
  List<String> _selectedAnnualIncome = [];

  // Other Details
  List<String> _selectedDiet = [];
  String? _selectedSmokeAcceptance;
  String? _selectedAlcoholAcceptance;
  String? _selectedDisabilityAcceptance;
  List<String> _selectedComplexion = [];
  List<String> _selectedBodyType = [];
  final TextEditingController _otherExpectationsController = TextEditingController();

  // Auto-generated expectations
  final List<String> _autoGeneratedExpectations = [];

  // Loading states
  bool _loadingCountries = false;
  bool _loadingStates = false;
  bool _loadingCities = false;

  // Error messages
  final Map<String, String> _errors = {
    'maritalStatus': '',
    'profileWithChildren': '',
    'familyType': '',
    'religion': '',
    'cast': '',
    'subCast': '',
    'motherTongue': '',
    'horoscopeBelief': '',
    'manglik': '',
    'country': '',
    'state': '',
    'city': '',
    'qualification': '',
    'educationMedium': '',
    'profession': '',
    'workingWith': '',
    'annualIncome': '',
    'diet': '',
    'smokeAcceptance': '',
    'alcoholAcceptance': '',
    'disabilityAcceptance': '',
    'complexion': '',
    'bodyType': '',
    'otherExpectations': '',
  };

  @override
  void initState() {
    super.initState();
    _loadCountries();
    // Initialize with "Any" for all multi-select fields
    _loadSavedPreferences();
  }

  // API Service Methods
  Future<void> _loadCountries() async {
    setState(() => _loadingCountries = true);
    try {
      final response = await http.get(
        Uri.parse("https://digitallami.com/Api3/countries.php"),
      ).timeout(const Duration(seconds: 30));

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        if (data['status'] == 'success') {
          setState(() {
            _countries = (data['data'] as List)
                .map((item) => Country(id: item['id'].toString(), name: item['name']))
                .toList();
            // Add "Any" option at the beginning
            _countries.insert(0, Country(id: '0', name: 'Any'));
          });
        }
      } else {
        _showError("Failed to load countries. Please try again.");
      }
    } on TimeoutException {
      _showError("Timeout loading countries. Please check your connection.");
    } catch (e) {
      print("Error loading countries: $e");
      _showError("Error loading countries. Please try again.");
    } finally {
      setState(() => _loadingCountries = false);
    }
  }

  Future<void> _loadStatesForCountries(List<String> countryIds) async {
    if (countryIds.isEmpty || countryIds.contains('Any')) {
      setState(() => _allStates.clear());
      return;
    }

    setState(() => _loadingStates = true);
    final List<StateModel> loadedStates = [];

    try {
      for (final countryId in countryIds) {
        if (countryId == '0') continue; // Skip "Any"

        final response = await http.get(
          Uri.parse("https://digitallami.com/Api3/states.php?country_id=$countryId"),
        ).timeout(const Duration(seconds: 30));

        if (response.statusCode == 200) {
          final data = jsonDecode(response.body);
          if (data['status'] == 'success') {
            final states = (data['data'] as List)
                .map((item) => StateModel(
              id: item['id'],
              name: item['name'],
              countryId: countryId,
            ))
                .toList();
            loadedStates.addAll(states);
          }
        }
      }

      setState(() {
        _allStates = loadedStates;
        // Add "Any" option if we have states
        if (_allStates.isNotEmpty) {
          _allStates.insert(0, StateModel(id: 0, name: 'Any', countryId: '0'));
        }
      });
    } on TimeoutException {
      _showError("Timeout loading states. Please try again.");
    } catch (e) {
      print("Error loading states: $e");
      _showError("Error loading states. Please try again.");
    } finally {
      setState(() => _loadingStates = false);
    }
  }

  Future<void> _loadCitiesForStates(List<String> stateIds) async {
    if (stateIds.isEmpty || stateIds.contains('Any')) {
      setState(() => _allCities.clear());
      return;
    }

    setState(() => _loadingCities = true);
    final List<City> loadedCities = [];

    try {
      for (final stateId in stateIds) {
        if (stateId == 'Any' || stateId == '0') continue;

        final response = await http.get(
          Uri.parse("https://digitallami.com/Api3/cities.php?state_id=$stateId"),
        ).timeout(const Duration(seconds: 30));

        if (response.statusCode == 200) {
          final data = jsonDecode(response.body);
          if (data['status'] == 'success') {
            final cities = (data['data'] as List)
                .map((item) => City(
              id: item['id'],
              name: item['name'],
              stateId: int.parse(stateId),
            ))
                .toList();
            loadedCities.addAll(cities);
          }
        }
      }

      setState(() {
        _allCities = loadedCities;
        // Add "Any" option if we have cities
        if (_allCities.isNotEmpty) {
          _allCities.insert(0, City(id: 0, name: 'Any', stateId: 0));
        }
      });
    } on TimeoutException {
      _showError("Timeout loading cities. Please try again.");
    } catch (e) {
      print("Error loading cities: $e");
      _showError("Error loading cities. Please try again.");
    } finally {
      setState(() => _loadingCities = false);
    }
  }

  // Helper methods
  bool _hasAnySelected(List<String> list) {
    return list.contains('Any');
  }

  List<String> _getCountryIds(List<String> selectedNames) {
    if (selectedNames.contains('Any')) return ['0'];

    return selectedNames.map((name) {
      final country = _countries.firstWhere((c) => c.name == name);
      return country.id;
    }).toList();
  }

  List<String> _getStateIds(List<String> selectedNames) {
    if (selectedNames.contains('Any')) return ['0'];

    return selectedNames.map((name) {
      final state = _allStates.firstWhere((s) => s.name == name);
      return state.id.toString();
    }).toList();
  }

  List<String> _getCityIds(List<String> selectedNames) {
    if (selectedNames.contains('Any')) return ['0'];

    return selectedNames.map((name) {
      final city = _allCities.firstWhere((c) => c.name == name);
      return city.id.toString();
    }).toList();
  }

  void _updateAutoGeneratedExpectations() {
    List<String> expectations = [];

    // Age expectations
    expectations.add('Looking for a partner aged between ${_minAge.toInt()} and ${_maxAge.toInt()} years.');

    // Height expectations
    expectations.add('Preferred height range: ${_minHeight.toInt()} cm to ${_maxHeight.toInt()} cm.');

    // Marital status
    if (_selectedMaritalStatus.isNotEmpty && !_hasAnySelected(_selectedMaritalStatus)) {
      expectations.add('Marital status preference: ${_selectedMaritalStatus.join(", ")}.');
    }

    // Family type
    if (_selectedFamilyType.isNotEmpty && !_hasAnySelected(_selectedFamilyType)) {
      expectations.add('Preferred family type: ${_selectedFamilyType.join(", ")}.');
    }

    // Religion
    if (_selectedReligion.isNotEmpty && !_hasAnySelected(_selectedReligion)) {
      expectations.add('Religion: ${_selectedReligion.join(", ")}.');
    }

    // Community preferences
    if (_selectedCast.isNotEmpty && !_hasAnySelected(_selectedCast)) {
      expectations.add('Community/caste preference: ${_selectedCast.join(", ")}.');
    }

    // Mother tongue
    if (_selectedMotherTongue.isNotEmpty && !_hasAnySelected(_selectedMotherTongue)) {
      expectations.add('Mother tongue preference: ${_selectedMotherTongue.join(", ")}.');
    }

    // Location preferences
    if (_selectedCountry.isNotEmpty && !_hasAnySelected(_selectedCountry)) {
      final countryNames = _selectedCountry.map((id) {
        if (id == 'Any') return 'Any';
        final country = _countries.firstWhere((c) => c.id == id, orElse: () => Country(id: '', name: id));
        return country.name;
      }).toList();
      expectations.add('Preferred country: ${countryNames.join(", ")}.');
    }

    // Education
    if (_selectedQualification.isNotEmpty && !_hasAnySelected(_selectedQualification)) {
      expectations.add('Educational qualification: ${_selectedQualification.join(", ")}.');
    }

    // Profession
    if (_selectedProfession.isNotEmpty && !_hasAnySelected(_selectedProfession)) {
      expectations.add('Profession preference: ${_selectedProfession.join(", ")}.');
    }

    // Income
    if (_selectedAnnualIncome.isNotEmpty && !_hasAnySelected(_selectedAnnualIncome)) {
      expectations.add('Annual income expectation: ${_selectedAnnualIncome.join(", ")}.');
    }

    // Lifestyle preferences
    if (_selectedDiet.isNotEmpty && !_hasAnySelected(_selectedDiet)) {
      expectations.add('Diet preference: ${_selectedDiet.join(", ")}.');
    }

    // Physical preferences
    if (_selectedComplexion.isNotEmpty && !_hasAnySelected(_selectedComplexion)) {
      expectations.add('Complexion preference: ${_selectedComplexion.join(", ")}.');
    }

    if (_selectedBodyType.isNotEmpty && !_hasAnySelected(_selectedBodyType)) {
      expectations.add('Body type preference: ${_selectedBodyType.join(", ")}.');
    }

    // Add smoke/alcohol preferences if selected
    if (_selectedSmokeAcceptance != null && _selectedSmokeAcceptance != 'Any') {
      expectations.add('Smoking acceptance: $_selectedSmokeAcceptance.');
    }

    if (_selectedAlcoholAcceptance != null && _selectedAlcoholAcceptance != 'Any') {
      expectations.add('Alcohol acceptance: $_selectedAlcoholAcceptance.');
    }

    if (_selectedDisabilityAcceptance != null && _selectedDisabilityAcceptance != 'Any') {
      expectations.add('Disability acceptance: $_selectedDisabilityAcceptance.');
    }

    // Astrological preferences
    if (_selectedHoroscopeBelief != null && _selectedHoroscopeBelief != 'Any') {
      expectations.add('Horoscope belief: $_selectedHoroscopeBelief.');
    }

    if (_selectedManglik != null && _selectedManglik != 'Any') {
      expectations.add('Manglik preference: $_selectedManglik.');
    }

    setState(() {
      _autoGeneratedExpectations.clear();
      _autoGeneratedExpectations.addAll(expectations);

      // Update the expectations controller with auto-generated text
      if (_autoGeneratedExpectations.isNotEmpty) {
        _otherExpectationsController.text = _autoGeneratedExpectations.join('\n');
      }
    });
  }

  // Dropdown options
  final List<String> _maritalStatusOptions = [
    'Any',
    'Single',
    'Divorced',
    'Widowed',
    'Never Married',
  ];

  final List<String> _childrenOptions = [
    'Any',
    'No child',
    'One',
    'Two or more',
  ];

  final List<String> _familyTypeOptions = [
    'Any',
    'Joint Family',
    'Nuclear Family',
    'Single Parent',
    'Extended Family',
  ];

  final List<String> _religionOptions = [
    'Any',
    'Hindu',
    'Muslim',
    'Christian',
    'Sikh',
    'Buddhist',
    'Jain',
  ];

  final List<String> _castOptions = [
    'Any',
    'Brahmin',
    'Chhetri',
    'Newar',
    'Gurung',
    'Tamang',
    'Rai',
    'Limbu',
    'Magar',
    'Tharu',
    'Sherpa',
  ];

  final List<String> _subcastOptions = [
    'Any',
    'Sherpa',
    'Thakali',
    'Bhote',
    'Lopa',
    'Manange',
    'Dolpo',
    'Brahmin',
    'Chhetri',
    'Newar',
    'Gurung',
    'Tamang',
    'Rai',
    'Limbu',
    'Magar',
    'Sunuwar',
    'Yakkha',
    'Thami',
    'Chepang',
    'Bhujel',
    'Danuwar',
    'Jirel',
    'Lepcha',
    'Tharu',
    'Yadav',
    'Koiri',
    'Kurmi',
    'Rajput',
    'Teli',
    'Mallah',
    'Baniya',
    'Musalman (Muslim)',
    'Kalwar',
    'Hajam',
    'Dhimal',
    'Rajbanshi',
    'Satar',
    'Marwadi',
    'Kami',
    'Damai',
    'Sarki',
    'Chamar',
    'Dusadh',
    'Mushahar',
    'Pode',
    'Badi',
    'Sanyasi',
    'Giri',
    'Thakuri',
    'Kumal',
    'Majhi',
    'Kewat',
    'Gaine',
    'Sikh',
    'Jain',
  ];

  final List<String> _motherTongueOptions = [
    'Any',
    'Nepali',
    'Maithili',
    'Bhojpuri',
    'Tharu',
    'Tamang',
    'Newari',
    'Magar',
    'Gurung',
    'Limbu',
    'Rai',
    'Sherpa',
  ];

  final List<String> _beliefOptions = [
    'Any',
    'Yes',
    'No',
    'Doesn\'t matter'
  ];

  final List<String> _qualificationOptions = [
    'Any',
    'SEE/SLC',
    '+2/Intermediate',
    'Diploma',
    'Bachelor',
    'Master',
    'PhD',
  ];

  final List<String> _educationMediumOptions = [
    'Any',
    'English',
    'Nepali',
    'Hindi',
  ];

  final List<String> _professionOptions = [
    'Any',
    'Government Job',
    'Private Job',
    'Business',
    'Doctor',
    'Engineer',
    'Teacher',
    'Student',
  ];

  final List<String> _workingWithOptions = [
    'Any',
    'Private Company',
    'Government',
    'NGO/INGO',
    'Self Employed',
    'Family Business',
  ];

  final List<String> _annualIncomeOptions = [
    'Any',
    'Below 2 Lakhs',
    '2-5 Lakhs',
    '5-10 Lakhs',
    '10-20 Lakhs',
    '20-50 Lakhs',
    '50 Lakhs - 1 Crore',
    'Above 1 Crore',
  ];

  final List<String> _dietOptions = [
    'Any',
    'Vegetarian',
    'Non-Vegetarian',
    'Eggetarian',
    'Vegan',
    'Jain',
  ];

  final List<String> _complexionOptions = [
    'Any',
    'Very Fair',
    'Fair',
    'Wheatish',
    'Olive',
    'Brown',
    'Dark',
  ];

  final List<String> _bodyTypeOptions = [
    'Any',
    'Slim',
    'Athletic',
    'Average',
    'Heavy',
    'Muscular',
  ];

  // Validation methods
  bool _validateRequiredList(List<String> list, String fieldName) {
    if (list.isEmpty) {
      _errors[fieldName] = 'Please select at least one option';
      return false;
    }
    _errors[fieldName] = '';
    return true;
  }

  bool _validateRequired(String? value, String fieldName) {
    if (value == null || value.isEmpty) {
      _errors[fieldName] = 'This field is required';
      return false;
    }
    _errors[fieldName] = '';
    return true;
  }

  bool _validateForm() {
    bool isValid = true;

    // Clear all errors
    _errors.forEach((key, value) {
      _errors[key] = '';
    });

    // Basic Preferences validation
    if (!_validateRequiredList(_selectedMaritalStatus, 'maritalStatus')) {
      isValid = false;
    }

    // Profile with children validation (only required if not single/any)
    if (!_hasAnySelected(_selectedMaritalStatus) && !_selectedMaritalStatus.contains('Single')) {
      if (!_validateRequired(_selectedProfileWithChildren, 'profileWithChildren')) {
        isValid = false;
      }
    } else {
      // Default to "No child" for single or any
      _selectedProfileWithChildren = 'No child';
    }

    if (!_validateRequiredList(_selectedFamilyType, 'familyType')) {
      isValid = false;
    }

    // Community Details validation
    if (!_validateRequiredList(_selectedReligion, 'religion')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedCast, 'cast')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedsubCast, 'subCast')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedMotherTongue, 'motherTongue')) {
      isValid = false;
    }

    // Astrological Details validation
    if (!_validateRequired(_selectedHoroscopeBelief, 'horoscopeBelief')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedManglik, 'manglik')) {
      isValid = false;
    }

    // Location Details validation
    if (!_validateRequiredList(_selectedCountry, 'country')) {
      isValid = false;
    }
    if (!_hasAnySelected(_selectedCountry) && !_validateRequiredList(_selectedState, 'state')) {
      isValid = false;
    }
    if (!_hasAnySelected(_selectedState) && !_validateRequiredList(_selectedCity, 'city')) {
      isValid = false;
    }

    // Education Details validation
    if (!_validateRequiredList(_selectedQualification, 'qualification')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedEducationMedium, 'educationMedium')) {
      isValid = false;
    }

    // Profession Details validation
    if (!_validateRequiredList(_selectedProfession, 'profession')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedWorkingWith, 'workingWith')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedAnnualIncome, 'annualIncome')) {
      isValid = false;
    }

    // Other Details validation
    if (!_validateRequiredList(_selectedDiet, 'diet')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedSmokeAcceptance, 'smokeAcceptance')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedAlcoholAcceptance, 'alcoholAcceptance')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedDisabilityAcceptance, 'disabilityAcceptance')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedComplexion, 'complexion')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedBodyType, 'bodyType')) {
      isValid = false;
    }

    setState(() {});
    return isValid;
  }

  // Handler methods
  void _handleCountryChange(List<String> selectedItems) {
    setState(() {
      _selectedCountry = selectedItems;
      _errors['country'] = '';

      // Reset states and cities when countries change
      _selectedState = ['Any'];
      _selectedCity = ['Any'];
      _allStates.clear();
      _allCities.clear();
    });

    // Load states for selected countries
    _loadStatesForCountries(_getCountryIds(selectedItems));
    _updateAutoGeneratedExpectations();
  }

  void _handleStateChange(List<String> selectedItems) {
    setState(() {
      _selectedState = selectedItems;
      _errors['state'] = '';

      // Reset cities when states change
      _selectedCity = ['Any'];
      _allCities.clear();
    });

    // Load cities for selected states
    _loadCitiesForStates(_getStateIds(selectedItems));
    _updateAutoGeneratedExpectations();
  }

  void _handleCityChange(List<String> selectedItems) {
    setState(() {
      _selectedCity = selectedItems;
      _errors['city'] = '';
    });

    _updateAutoGeneratedExpectations();
  }

  void _handleMultiSelectChange(List<String> selectedItems, String fieldName, Function(List<String>) updateFunction) {
    // If "Any" is selected, clear all other selections and only keep "Any"
    if (selectedItems.contains('Any')) {
      selectedItems = ['Any'];
    }
    // If something else is selected and "Any" was previously selected, remove "Any"
    else if (selectedItems.isNotEmpty) {
      selectedItems.remove('Any');
    }

    updateFunction(selectedItems);
    _updateAutoGeneratedExpectations();
  }

  void _handleSingleSelectChange(String? value, String fieldName, Function(String?) updateFunction) {
    updateFunction(value);
    _updateAutoGeneratedExpectations();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Stack(
          children: [
            SingleChildScrollView(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header
                  const Center(
                    child: Text(
                      "Partner Preferences",
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFFE64B37),
                      ),
                    ),
                  ),

                  const SizedBox(height: 25),
                  const Center(child: Image(image: AssetImage('assets/images/partner.png'))),

                  // Age Range
                  _buildSectionTitle("Age Range*"),
                  const SizedBox(height: 8),
                  _buildRangeSlider(
                    minValue: _minAge,
                    maxValue: _maxAge,
                    min: 18,
                    max: 80,
                    divisions: 62,
                    labelBuilder: (value) => '${value.toInt()}',
                    onChanged: (min, max) {
                      setState(() {
                        _minAge = min;
                        _maxAge = max;
                        _updateAutoGeneratedExpectations();
                      });
                    },
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text('${_minAge.toInt()} years',
                          style: const TextStyle(fontSize: 14, color: Colors.black54)),
                      Text('${_maxAge.toInt()} years',
                          style: const TextStyle(fontSize: 14, color: Colors.black54)),
                    ],
                  ),

                  const SizedBox(height: 25),

                  // Height Range
                  _buildSectionTitle("Height Range (In Cm)*"),
                  const SizedBox(height: 8),
                  _buildRangeSlider(
                    minValue: _minHeight,
                    maxValue: _maxHeight,
                    min: 100,
                    max: 250,
                    divisions: 150,
                    labelBuilder: (value) => '${value.toInt()} cm',
                    onChanged: (min, max) {
                      setState(() {
                        _minHeight = min;
                        _maxHeight = max;
                        _updateAutoGeneratedExpectations();
                      });
                    },
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text('${_minHeight.toInt()} cm',
                          style: const TextStyle(fontSize: 14, color: Colors.black54)),
                      Text('${_maxHeight.toInt()} cm',
                          style: const TextStyle(fontSize: 14, color: Colors.black54)),
                    ],
                  ),

                  const SizedBox(height: 25),

                  // Marital Status (Multi-select)
                  _buildSectionTitle("Marital Status*"),
                  if (submitted && _errors['maritalStatus']!.isNotEmpty)
                    _buildErrorText(_errors['maritalStatus']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedMaritalStatus,
                    options: _maritalStatusOptions,
                    hint: "Choose Marital Status*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'maritalStatus',
                            (items) {
                          setState(() {
                            _selectedMaritalStatus = items;
                            _errors['maritalStatus'] = '';
                          });
                        },
                      );
                    },
                    title: 'Marital Status',
                    showError: submitted && _errors['maritalStatus']!.isNotEmpty,
                    errorText: _errors['maritalStatus'],
                  ),

                  const SizedBox(height: 20),
                  if (!_hasAnySelected(_selectedMaritalStatus) && !_selectedMaritalStatus.contains('Single')) ...[
                    _buildSectionTitle("Profile With Children*"),
                    if (submitted && _errors['profileWithChildren']!.isNotEmpty)
                      _buildErrorText(_errors['profileWithChildren']!),
                    const SizedBox(height: 8),
                    Row(
                      children: _childrenOptions.map((option) {
                        return Expanded(
                          child: _buildRadioOption(
                            value: option,
                            groupValue: _selectedProfileWithChildren,
                            label: option,
                            onChanged: (value) {
                              _handleSingleSelectChange(
                                value,
                                'profileWithChildren',
                                    (val) {
                                  setState(() {
                                    _selectedProfileWithChildren = val;
                                    _errors['profileWithChildren'] = '';
                                  });
                                },
                              );
                            },
                            hasError: submitted && _errors['profileWithChildren']!.isNotEmpty,
                          ),
                        );
                      }).toList(),
                    ),
                  ],

                  const SizedBox(height: 20),

                  // Family Type (Multi-select)
                  _buildSectionTitle("Family Type*"),
                  if (submitted && _errors['familyType']!.isNotEmpty)
                    _buildErrorText(_errors['familyType']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedFamilyType,
                    options: _familyTypeOptions,
                    hint: "Select Family Type*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'familyType',
                            (items) {
                          setState(() {
                            _selectedFamilyType = items;
                            _errors['familyType'] = '';
                          });
                        },
                      );
                    },
                    title: 'Family Type',
                    showError: submitted && _errors['familyType']!.isNotEmpty,
                    errorText: _errors['familyType'],
                  ),

                  const SizedBox(height: 25),
                  _buildDivider(),
                  const SizedBox(height: 25),

                  // Preferred Community Details
                  _buildSectionTitle("Preferred Community Details"),
                  const SizedBox(height: 15),

                  // Religion (Multi-select)
                  _buildSectionTitle("Religion*"),
                  if (submitted && _errors['religion']!.isNotEmpty)
                    _buildErrorText(_errors['religion']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedReligion,
                    options: _religionOptions,
                    hint: "Select Religion Type*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'religion',
                            (items) {
                          setState(() {
                            _selectedReligion = items;
                            _errors['religion'] = '';
                          });
                        },
                      );
                    },
                    title: 'Religion Type',
                    showError: submitted && _errors['religion']!.isNotEmpty,
                    errorText: _errors['religion'],
                  ),

                  const SizedBox(height: 15),

                  // Cast (Multi-select)
                  _buildSectionTitle("Cast*"),
                  if (submitted && _errors['cast']!.isNotEmpty)
                    _buildErrorText(_errors['cast']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedCast,
                    options: _castOptions,
                    hint: "Select Cast Type*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'cast',
                            (items) {
                          setState(() {
                            _selectedCast = items;
                            _errors['cast'] = '';
                          });
                        },
                      );
                    },
                    title: 'Cast Type',
                    showError: submitted && _errors['cast']!.isNotEmpty,
                    errorText: _errors['cast'],
                  ),

                  const SizedBox(height: 15),

                  // Sub Cast (Multi-select)
                  _buildSectionTitle("Sub Cast*"),
                  if (submitted && _errors['subCast']!.isNotEmpty)
                    _buildErrorText(_errors['subCast']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedsubCast,
                    options: _subcastOptions,
                    hint: "Select SubCast Type*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'subCast',
                            (items) {
                          setState(() {
                            _selectedsubCast = items;
                            _errors['subCast'] = '';
                          });
                        },
                      );
                    },
                    title: 'SubCast Type',
                    showError: submitted && _errors['subCast']!.isNotEmpty,
                    errorText: _errors['subCast'],
                  ),

                  const SizedBox(height: 15),

                  // Mother Tongue (Multi-select)
                  _buildSectionTitle("Mother Tongue*"),
                  if (submitted && _errors['motherTongue']!.isNotEmpty)
                    _buildErrorText(_errors['motherTongue']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedMotherTongue,
                    options: _motherTongueOptions,
                    hint: "Select Mother Tongue Type*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'motherTongue',
                            (items) {
                          setState(() {
                            _selectedMotherTongue = items;
                            _errors['motherTongue'] = '';
                          });
                        },
                      );
                    },
                    title: 'Mother Tongue Type',
                    showError: submitted && _errors['motherTongue']!.isNotEmpty,
                    errorText: _errors['motherTongue'],
                  ),

                  const SizedBox(height: 25),
                  _buildDivider(),
                  const SizedBox(height: 25),

                  // Preferred Astrological Details
                  _buildSectionTitle("Preferred Astrological Details"),
                  const SizedBox(height: 15),

                  _buildSectionTitle("Horoscope Belief*"),
                  if (submitted && _errors['horoscopeBelief']!.isNotEmpty)
                    _buildErrorText(_errors['horoscopeBelief']!),
                  const SizedBox(height: 8),
                  Row(
                    children: _beliefOptions.map((option) {
                      return Expanded(
                        child: _buildRadioOption(
                          value: option,
                          groupValue: _selectedHoroscopeBelief,
                          label: option,
                          onChanged: (value) {
                            _handleSingleSelectChange(
                              value,
                              'horoscopeBelief',
                                  (val) {
                                setState(() {
                                  _selectedHoroscopeBelief = val;
                                  _errors['horoscopeBelief'] = '';
                                });
                              },
                            );
                          },
                          hasError: submitted && _errors['horoscopeBelief']!.isNotEmpty,
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 20),

                  _buildSectionTitle("Manglik*"),
                  if (submitted && _errors['manglik']!.isNotEmpty)
                    _buildErrorText(_errors['manglik']!),
                  const SizedBox(height: 8),
                  Row(
                    children: _beliefOptions.map((option) {
                      return Expanded(
                        child: _buildRadioOption(
                          value: option,
                          groupValue: _selectedManglik,
                          label: option,
                          onChanged: (value) {
                            _handleSingleSelectChange(
                              value,
                              'manglik',
                                  (val) {
                                setState(() {
                                  _selectedManglik = val;
                                  _errors['manglik'] = '';
                                });
                              },
                            );
                          },
                          hasError: submitted && _errors['manglik']!.isNotEmpty,
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 25),
                  _buildDivider(),
                  const SizedBox(height: 25),

                  // Preferred Location Details
                  _buildSectionTitle("Preferred Location Details"),
                  const SizedBox(height: 15),

                  // Country (Multi-select from API)
                  _buildSectionTitle("Country*"),
                  if (submitted && _errors['country']!.isNotEmpty)
                    _buildErrorText(_errors['country']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedCountry,
                    options: _countries.map((c) => c.name).toList(),
                    hint: "Select Country*",
                    onChanged: _handleCountryChange,
                    title: 'Country',
                    showError: submitted && _errors['country']!.isNotEmpty,
                    errorText: _errors['country'],
                    isLoading: _loadingCountries,
                    disabled: _loadingCountries,
                  ),

                  // State Dropdown (only show if countries are selected and not "Any")
                  if (_selectedCountry.isNotEmpty && !_hasAnySelected(_selectedCountry)) ...[
                    const SizedBox(height: 15),
                    _buildSectionTitle("State / Province*"),
                    if (submitted && _errors['state']!.isNotEmpty)
                      _buildErrorText(_errors['state']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedState,
                      options: _allStates.map((s) => s.name).toList(),
                      hint: _loadingStates ? "Loading states..." : "State / Province*",
                      onChanged: _handleStateChange,
                      title: 'State / Province',
                      showError: submitted && _errors['state']!.isNotEmpty,
                      errorText: _errors['state'],
                      isLoading: _loadingStates,
                      disabled: _loadingStates,
                    ),
                  ],

                  // City Dropdown (only show if states are selected and not "Any")
                  if (_selectedState.isNotEmpty && !_hasAnySelected(_selectedState)) ...[
                    const SizedBox(height: 15),
                    _buildSectionTitle("City*"),
                    if (submitted && _errors['city']!.isNotEmpty)
                      _buildErrorText(_errors['city']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedCity,
                      options: _allCities.map((c) => c.name).toList(),
                      hint: _loadingCities ? "Loading cities..." : "City*",
                      onChanged: _handleCityChange,
                      title: 'Cities',
                      showError: submitted && _errors['city']!.isNotEmpty,
                      errorText: _errors['city'],
                      isLoading: _loadingCities,
                      disabled: _loadingCities,
                    ),
                  ],

                  const SizedBox(height: 25),
                  _buildDivider(),
                  const SizedBox(height: 25),

                  // Preferred Education Details
                  _buildSectionTitle("Preferred Education Details"),
                  const SizedBox(height: 15),

                  // Qualification (Multi-select)
                  _buildSectionTitle("Qualification*"),
                  if (submitted && _errors['qualification']!.isNotEmpty)
                    _buildErrorText(_errors['qualification']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedQualification,
                    options: _qualificationOptions,
                    hint: "Select Your Qualification*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'qualification',
                            (items) {
                          setState(() {
                            _selectedQualification = items;
                            _errors['qualification'] = '';
                          });
                        },
                      );
                    },
                    title: 'Qualifications',
                    showError: submitted && _errors['qualification']!.isNotEmpty,
                    errorText: _errors['qualification'],
                  ),

                  const SizedBox(height: 15),

                  // Education Medium (Multi-select)
                  _buildSectionTitle("Education Medium*"),
                  if (submitted && _errors['educationMedium']!.isNotEmpty)
                    _buildErrorText(_errors['educationMedium']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedEducationMedium,
                    options: _educationMediumOptions,
                    hint: "Select Your Education Medium*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'educationMedium',
                            (items) {
                          setState(() {
                            _selectedEducationMedium = items;
                            _errors['educationMedium'] = '';
                          });
                        },
                      );
                    },
                    title: 'Education Medium',
                    showError: submitted && _errors['educationMedium']!.isNotEmpty,
                    errorText: _errors['educationMedium'],
                  ),

                  const SizedBox(height: 25),
                  _buildDivider(),
                  const SizedBox(height: 25),

                  // Profession Details
                  // Profession (Multi-select)
                  _buildSectionTitle("Profession*"),
                  if (submitted && _errors['profession']!.isNotEmpty)
                    _buildErrorText(_errors['profession']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedProfession,
                    options: _professionOptions,
                    hint: "Select Your Profession*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'profession',
                            (items) {
                          setState(() {
                            _selectedProfession = items;
                            _errors['profession'] = '';
                          });
                        },
                      );
                    },
                    title: 'Profession',
                    showError: submitted && _errors['profession']!.isNotEmpty,
                    errorText: _errors['profession'],
                  ),

                  const SizedBox(height: 15),

                  // Working With (Multi-select)
                  _buildSectionTitle("Working With*"),
                  if (submitted && _errors['workingWith']!.isNotEmpty)
                    _buildErrorText(_errors['workingWith']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedWorkingWith,
                    options: _workingWithOptions,
                    hint: "Select Working With*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'workingWith',
                            (items) {
                          setState(() {
                            _selectedWorkingWith = items;
                            _errors['workingWith'] = '';
                          });
                        },
                      );
                    },
                    title: 'Working With',
                    showError: submitted && _errors['workingWith']!.isNotEmpty,
                    errorText: _errors['workingWith'],
                  ),

                  const SizedBox(height: 15),

                  // Annual Income (Multi-select)
                  _buildSectionTitle("Annual Income*"),
                  if (submitted && _errors['annualIncome']!.isNotEmpty)
                    _buildErrorText(_errors['annualIncome']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedAnnualIncome,
                    options: _annualIncomeOptions,
                    hint: "Select Your Annual Income*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'annualIncome',
                            (items) {
                          setState(() {
                            _selectedAnnualIncome = items;
                            _errors['annualIncome'] = '';
                          });
                        },
                      );
                    },
                    title: 'Annual Income',
                    showError: submitted && _errors['annualIncome']!.isNotEmpty,
                    errorText: _errors['annualIncome'],
                  ),

                  const SizedBox(height: 25),
                  _buildDivider(),
                  const SizedBox(height: 25),

                  // Other Details
                  _buildSectionTitle("Other Details"),
                  const SizedBox(height: 15),

                  // Diet (Multi-select)
                  _buildSectionTitle("Diet*"),
                  if (submitted && _errors['diet']!.isNotEmpty)
                    _buildErrorText(_errors['diet']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedDiet,
                    options: _dietOptions,
                    hint: "Choose Diet*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'diet',
                            (items) {
                          setState(() {
                            _selectedDiet = items;
                            _errors['diet'] = '';
                          });
                        },
                      );
                    },
                    title: 'Diets',
                    showError: submitted && _errors['diet']!.isNotEmpty,
                    errorText: _errors['diet'],
                  ),

                  const SizedBox(height: 20),

                  _buildSectionTitle("Smoke Acceptance*"),
                  if (submitted && _errors['smokeAcceptance']!.isNotEmpty)
                    _buildErrorText(_errors['smokeAcceptance']!),
                  const SizedBox(height: 8),
                  Row(
                    children: _beliefOptions.map((option) {
                      return Expanded(
                        child: _buildRadioOption(
                          value: option,
                          groupValue: _selectedSmokeAcceptance,
                          label: option,
                          onChanged: (value) {
                            _handleSingleSelectChange(
                              value,
                              'smokeAcceptance',
                                  (val) {
                                setState(() {
                                  _selectedSmokeAcceptance = val;
                                  _errors['smokeAcceptance'] = '';
                                });
                              },
                            );
                          },
                          hasError: submitted && _errors['smokeAcceptance']!.isNotEmpty,
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 20),

                  _buildSectionTitle("Alcohol Acceptance*"),
                  if (submitted && _errors['alcoholAcceptance']!.isNotEmpty)
                    _buildErrorText(_errors['alcoholAcceptance']!),
                  const SizedBox(height: 8),
                  Row(
                    children: _beliefOptions.map((option) {
                      return Expanded(
                        child: _buildRadioOption(
                          value: option,
                          groupValue: _selectedAlcoholAcceptance,
                          label: option,
                          onChanged: (value) {
                            _handleSingleSelectChange(
                              value,
                              'alcoholAcceptance',
                                  (val) {
                                setState(() {
                                  _selectedAlcoholAcceptance = val;
                                  _errors['alcoholAcceptance'] = '';
                                });
                              },
                            );
                          },
                          hasError: submitted && _errors['alcoholAcceptance']!.isNotEmpty,
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 20),

                  _buildSectionTitle("Disability Acceptance*"),
                  if (submitted && _errors['disabilityAcceptance']!.isNotEmpty)
                    _buildErrorText(_errors['disabilityAcceptance']!),
                  const SizedBox(height: 8),
                  Row(
                    children: _beliefOptions.map((option) {
                      return Expanded(
                        child: _buildRadioOption(
                          value: option,
                          groupValue: _selectedDisabilityAcceptance,
                          label: option,
                          onChanged: (value) {
                            _handleSingleSelectChange(
                              value,
                              'disabilityAcceptance',
                                  (val) {
                                setState(() {
                                  _selectedDisabilityAcceptance = val;
                                  _errors['disabilityAcceptance'] = '';
                                });
                              },
                            );
                          },
                          hasError: submitted && _errors['disabilityAcceptance']!.isNotEmpty,
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 20),

                  // Complexion (Multi-select)
                  _buildSectionTitle("Complexion*"),
                  if (submitted && _errors['complexion']!.isNotEmpty)
                    _buildErrorText(_errors['complexion']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedComplexion,
                    options: _complexionOptions,
                    hint: "Choose Complexion*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'complexion',
                            (items) {
                          setState(() {
                            _selectedComplexion = items;
                            _errors['complexion'] = '';
                          });
                        },
                      );
                    },
                    title: 'Complexion',
                    showError: submitted && _errors['complexion']!.isNotEmpty,
                    errorText: _errors['complexion'],
                  ),

                  const SizedBox(height: 15),

                  // Body Type (Multi-select)
                  _buildSectionTitle("Body Type*"),
                  if (submitted && _errors['bodyType']!.isNotEmpty)
                    _buildErrorText(_errors['bodyType']!),
                  const SizedBox(height: 8),
                  _buildMultiSelectDropdown(
                    selectedItems: _selectedBodyType,
                    options: _bodyTypeOptions,
                    hint: "Choose Body Type*",
                    onChanged: (selectedItems) {
                      _handleMultiSelectChange(
                        selectedItems,
                        'bodyType',
                            (items) {
                          setState(() {
                            _selectedBodyType = items;
                            _errors['bodyType'] = '';
                          });
                        },
                      );
                    },
                    title: 'Body Type',
                    showError: submitted && _errors['bodyType']!.isNotEmpty,
                    errorText: _errors['bodyType'],
                  ),

                  const SizedBox(height: 25),

                  // Auto-generated expectations preview
                  if (_autoGeneratedExpectations.isNotEmpty) ...[
                    _buildSectionTitle("Auto-generated Expectations"),
                    Container(
                      margin: const EdgeInsets.only(bottom: 10),
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: Colors.grey[50],
                        borderRadius: BorderRadius.circular(10),
                        border: Border.all(color: Colors.grey[300]!),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Row(
                            children: [
                              Icon(Icons.auto_awesome, size: 16, color: Colors.blue),
                              SizedBox(width: 8),
                              Text(
                                "Auto-generated based on your selections:",
                                style: TextStyle(
                                  fontSize: 12,
                                  fontWeight: FontWeight.w600,
                                  color: Colors.blue,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          ..._autoGeneratedExpectations.map((expectation) {
                            return Padding(
                              padding: const EdgeInsets.symmetric(vertical: 2),
                              child: Row(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  const Text("• ", style: TextStyle(fontSize: 12)),
                                  Expanded(
                                    child: Text(
                                      expectation,
                                      style: const TextStyle(fontSize: 12, color: Colors.black87),
                                    ),
                                  ),
                                ],
                              ),
                            );
                          }).toList(),
                        ],
                      ),
                    ),
                  ],

                  _buildSectionTitle("Any Other Expectation*"),
                  const SizedBox(height: 8),
                  Container(
                    height: 120,
                    padding: const EdgeInsets.symmetric(horizontal: 15),
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(15),
                      border: Border.all(
                        color: const Color(0xFF48A54C),
                        width: 1.6,
                      ),
                    ),
                    child: TextField(
                      controller: _otherExpectationsController,
                      decoration: const InputDecoration(
                        border: InputBorder.none,
                        hintText: "Enter your other expectations...",
                        hintStyle: TextStyle(fontSize: 16, color: Colors.black54),
                      ),
                      maxLines: null,
                      expands: true,
                      textAlignVertical: TextAlignVertical.top,
                      onChanged: (value) {
                        // Allow manual editing while keeping auto-generated content
                      },
                    ),
                  ),

                  const SizedBox(height: 10),
                  Align(
                    alignment: Alignment.centerRight,
                    child: GestureDetector(
                      onTap: () {
                        _updateAutoGeneratedExpectations();
                      },
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: Colors.blue[50],
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(color: Colors.blue),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(Icons.autorenew, size: 14, color: Colors.blue[700]),
                            const SizedBox(width: 6),
                            Text(
                              "Regenerate Expectations",
                              style: TextStyle(
                                fontSize: 12,
                                color: Colors.blue[700],
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),

                  const SizedBox(height: 35),

                  // Buttons
                  Row(
                    children: [
                      Expanded(
                        child: _buildButton(
                          text: "Previous",
                          isPrimary: false,
                          onPressed: isLoading ? null : () {
                            Navigator.pop(context);
                          },
                        ),
                      ),
                      const SizedBox(width: 15),
                      Expanded(
                        child: _buildButton(
                          text: isLoading ? "Saving..." : "Continue",
                          isPrimary: true,
                          onPressed: isLoading ? null : _validateAndSubmit,
                        ),
                      ),
                    ],
                  ),

                  const SizedBox(height: 30),
                ],
              ),
            ),

            // Progress bubble
            Positioned(
              right: 12,
              top: 8,
              child: _progressBubble(0.45, "45%"),
            ),

            // Loading overlay
            if (isLoading)
              Container(
                color: Colors.black.withOpacity(0.3),
                child: const Center(
                  child: CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(Color(0xFFE64B37)),
                  ),
                ),
              ),
          ],
        ),
      ),
    );
  }

  // Multi-select dropdown widget
// Multi-select dropdown widget
  Widget _buildMultiSelectDropdown({
    required List<String> selectedItems,
    required List<String> options,
    required String hint,
    required Function(List<String>) onChanged,
    String? title,
    bool showError = false,
    String? errorText,
    bool isLoading = false,
    bool disabled = false,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(15),
            border: Border.all(
              color: showError && (errorText?.isNotEmpty ?? false)
                  ? Colors.red
                  : const Color(0xFF48A54C),
              width: 1.6,
            ),
          ),
          child: ExpansionTile(
            title: Row(
              children: [
                if (isLoading) ...[
                  SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation<Color>(const Color(0xFFE64B37)),
                    ),
                  ),
                  const SizedBox(width: 10),
                ],
                Expanded(
                  child: Text(
                    isLoading
                        ? hint
                        : selectedItems.isEmpty
                        ? hint
                        : selectedItems.contains('Any')
                        ? "Any (All options)"
                        : "${selectedItems.length} selected: ${selectedItems.join(", ").length > 30 ? "${selectedItems.join(", ").substring(0, 30)}..." : selectedItems.join(", ")}",
                    style: TextStyle(
                      fontSize: 16,
                      color: isLoading || selectedItems.isEmpty ? Colors.black54 : Colors.black87,
                    ),
                  ),
                ),
              ],
            ),
            onExpansionChanged: (expanded) {
              if (disabled || isLoading) return;
            },
            children: isLoading
                ? [
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Center(
                  child: CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(const Color(0xFFE64B37)),
                  ),
                ),
              ),
            ]
                : [
              // Constrained height to show only 4 items
              ConstrainedBox(
                constraints: const BoxConstraints(
                  maxHeight: 56 * 4.5, // Approximately 4.5 items (4 full + partial 5th)
                ),
                child: ListView.builder(
                  shrinkWrap: true,
                  itemCount: options.length,
                  itemBuilder: (context, index) {
                    final option = options[index];
                    bool isSelected = selectedItems.contains(option);
                    bool isAnySelected = selectedItems.contains('Any');

                    return CheckboxListTile(
                      title: Text(option),
                      value: isSelected,
                      onChanged: disabled ? null : (bool? value) {
                        List<String> newSelection = List.from(selectedItems);

                        if (option == 'Any') {
                          if (value == true) {
                            newSelection = ['Any'];
                          } else {
                            newSelection.remove('Any');
                          }
                        } else {
                          if (value == true) {
                            newSelection.remove('Any');
                            newSelection.add(option);
                          } else {
                            newSelection.remove(option);
                          }

                          if (newSelection.isEmpty) {
                            newSelection = ['Any'];
                          }
                        }

                        onChanged(newSelection);
                      },
                      secondary: option == 'Any'
                          ? const Icon(Icons.all_inclusive, color: Colors.blue)
                          : null,
                      activeColor: const Color(0xFFE64B37),
                    );
                  },
                ),
              ),
            ],
          ),
        ),
        if (showError && (errorText?.isNotEmpty ?? false))
          Padding(
            padding: const EdgeInsets.only(top: 4.0),
            child: Text(
              errorText!,
              style: const TextStyle(
                color: Colors.red,
                fontSize: 12,
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildErrorText(String error) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4.0, top: 4.0),
      child: Text(
        error,
        style: const TextStyle(
          color: Colors.red,
          fontSize: 12,
        ),
      ),
    );
  }

  Widget _buildRangeSlider({
    required double minValue,
    required double maxValue,
    required double min,
    required double max,
    required int divisions,
    required String Function(double) labelBuilder,
    required Function(double, double) onChanged,
  }) {
    return RangeSlider(
      values: RangeValues(minValue, maxValue),
      min: min,
      max: max,
      divisions: divisions,
      labels: RangeLabels(
        labelBuilder(minValue),
        labelBuilder(maxValue),
      ),
      activeColor: const Color(0xFFE64B37),
      inactiveColor: Colors.grey[300],
      onChanged: (RangeValues values) {
        onChanged(values.start, values.end);
      },
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontSize: 15,
        fontWeight: FontWeight.w600,
        color: Colors.black87,
      ),
    );
  }

  Widget _buildDivider() {
    return const Divider(
      color: Colors.grey,
      height: 1,
      thickness: 1,
    );
  }

  Widget _buildRadioOption({
    required String value,
    required String? groupValue,
    required String label,
    required Function(String) onChanged,
    bool hasError = false,
  }) {
    bool isSelected = groupValue == value;

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 2),
      height: 45,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
          color: hasError ? Colors.red : const Color(0xFF48A54C),
          width: 1.2,
        ),
        color: isSelected ? const Color(0xFFE64B37).withOpacity(0.1) : Colors.transparent,
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          borderRadius: BorderRadius.circular(8),
          onTap: () {
            onChanged(value);
          },
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  width: 16,
                  height: 16,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    border: Border.all(
                      color: isSelected ? const Color(0xFFE64B37) : Colors.grey,
                      width: 2,
                    ),
                    color: isSelected ? const Color(0xFFE64B37) : Colors.transparent,
                  ),
                  child: isSelected
                      ? const Icon(
                    Icons.circle,
                    size: 8,
                    color: Colors.white,
                  )
                      : null,
                ),
                const SizedBox(width: 6),
                Expanded(
                  child: Text(
                    label,
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.black87,
                      fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                    ),
                    textAlign: TextAlign.center,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildButton({
    required String text,
    required bool isPrimary,
    required VoidCallback? onPressed,
  }) {
    return Container(
      height: 55,
      decoration: BoxDecoration(
        gradient: isPrimary && onPressed != null
            ? const LinearGradient(
          colors: [
            Color(0xFFE64B37),
            Color(0xFFE62255),
          ],
        )
            : const LinearGradient(
          colors: [
            Color(0xFFEEA2A4),
            Color(0xFFF3C0C4),
          ],
        ),
        borderRadius: BorderRadius.circular(30),
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          borderRadius: BorderRadius.circular(30),
          onTap: onPressed,
          child: Center(
            child: Text(
              text,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 17,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _progressBubble(double progress, String label) {
    final size = 42.0;
    return SizedBox(
      height: size,
      width: size,
      child: Stack(
        alignment: Alignment.center,
        children: [
          Container(
            height: size,
            width: size,
            decoration: const BoxDecoration(
              color: Colors.white,
              shape: BoxShape.circle,
            ),
          ),
          SizedBox(
            height: size,
            width: size,
            child: CircularProgressIndicator(
              value: progress,
              strokeWidth: 3.2,
              valueColor: const AlwaysStoppedAnimation(Color(0xFFE64B37)),
              backgroundColor: Colors.white,
            ),
          ),
          Text(
            label,
            style: const TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.w700,
              color: Color(0xFFE64B37),
            ),
          ),
        ],
      ),
    );
  }

  void _validateAndSubmit() async {
    setState(() {
      submitted = true;
    });

    if (!_validateForm()) {
      _showError("Please fill all required fields correctly");
      return;
    }

    setState(() {
      isLoading = true;
    });

    await _submitPartnerPreferences();

    setState(() {
      isLoading = false;
    });
  }

  // Add this method to load saved partner preferences
  Future<void> _loadSavedPreferences() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final userDataString = prefs.getString('user_data');

      if (userDataString == null) {
        return;
      }

      final userData = jsonDecode(userDataString);
      final userId = userData["id"]?.toString() ?? '';

      if (userId.isEmpty) {
        return;
      }

      setState(() {
        isLoading = true;
      });

      final response = await http.get(
        Uri.parse("https://digitallami.com/Api2/get_partner_preferences.php?userid=$userId"),
      ).timeout(const Duration(seconds: 30));

      if (response.statusCode == 200) {
        final result = jsonDecode(response.body);

        if (result['status'] == 'success' && result['data'] != null) {
          final data = result['data'];

          setState(() {
            // Age Range
            _minAge = double.parse(data['minage'] ?? '22');
            _maxAge = double.parse(data['maxage'] ?? '60');

            // Height Range
            _minHeight = double.parse(data['minheight'] ?? '121');
            _maxHeight = double.parse(data['maxheight'] ?? '215');

            // Basic Preferences
            _selectedMaritalStatus = List<String>.from(data['maritalstatus'] ?? ['Any']);
            _selectedProfileWithChildren = data['profilewithchild'];
            _selectedFamilyType = List<String>.from(data['familytype'] ?? ['Any']);

            // Community Details
            _selectedReligion = List<String>.from(data['religion'] ?? ['Any']);
            _selectedCast = List<String>.from(data['caste'] ?? ['Any']);
            _selectedsubCast = List<String>.from(data['subcaste'] ?? ['Any']);
            _selectedMotherTongue = List<String>.from(data['mothertoungue'] ?? ['Any']);

            // Astrological Details
            _selectedHoroscopeBelief = data['herscopeblief'];
            _selectedManglik = data['manglik'];

            // Location Details
            _selectedCountry = List<String>.from(data['country'] ?? ['Any']);
            _selectedState = List<String>.from(data['state'] ?? ['Any']);
            _selectedCity = List<String>.from(data['city'] ?? ['Any']);

            // Education Details
            _selectedQualification = List<String>.from(data['qualification'] ?? ['Any']);
            _selectedEducationMedium = List<String>.from(data['educationmedium'] ?? ['Any']);

            // Profession Details
            _selectedProfession = List<String>.from(data['proffession'] ?? ['Any']);
            _selectedWorkingWith = List<String>.from(data['workingwith'] ?? ['Any']);
            _selectedAnnualIncome = List<String>.from(data['annualincome'] ?? ['Any']);

            // Other Details
            _selectedDiet = List<String>.from(data['diet'] ?? ['Any']);
            _selectedSmokeAcceptance = data['smokeaccept'];
            _selectedAlcoholAcceptance = data['drinkaccept'];
            _selectedDisabilityAcceptance = data['disabilityaccept'];
            _selectedComplexion = List<String>.from(data['complexion'] ?? ['Any']);
            _selectedBodyType = List<String>.from(data['bodytype'] ?? ['Any']);

            // Other Expectations
            _otherExpectationsController.text = data['otherexpectation'] ?? '';
          });

          // Load dependent data based on saved selections
          if (_selectedCountry.isNotEmpty && !_hasAnySelected(_selectedCountry)) {
            await _loadStatesForCountries(_getCountryIds(_selectedCountry));
          }

          if (_selectedState.isNotEmpty && !_hasAnySelected(_selectedState)) {
            await _loadCitiesForStates(_getStateIds(_selectedState));
          }

          // Regenerate expectations based on loaded data
          _updateAutoGeneratedExpectations();
        }
      }
    } catch (e) {
      print("Error loading saved preferences: $e");
    } finally {
      setState(() {
        isLoading = false;
      });
    }
  }

// Update initState to load saved data


  _submitPartnerPreferences() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final userDataString = prefs.getString('user_data');

      if (userDataString == null) {
        _showError("User data not found. Please login again.");
        return;
      }

      final userData = jsonDecode(userDataString);
      final userId = int.tryParse(userData["id"]?.toString() ?? '0');

      if (userId == null || userId == 0) {
        _showError("Invalid user ID");
        return;
      }

      // Prepare the data as JSON
      final Map<String, dynamic> body = {
        "userid": userId.toString(),
        "minage": _minAge.toInt().toString(),
        "maxage": _maxAge.toInt().toString(),
        "minheight": _minHeight.toInt().toString(),
        "maxheight": _maxHeight.toInt().toString(),
        "maritalstatus": _selectedMaritalStatus.join(","),
        "profilewithchild": _selectedProfileWithChildren ?? "No child",
        "familytype": _selectedFamilyType.join(","),
        "religion": _selectedReligion.join(","),
        "caste": _selectedCast.join(","),
        "subcaste": _selectedsubCast.join(","),
        "mothertoungue": _selectedMotherTongue.join(","),
        "herscopeblief": _selectedHoroscopeBelief ?? "",
        "manglik": _selectedManglik ?? "",
        "country": _getCountryIds(_selectedCountry).join(","),
        "state": _getStateIds(_selectedState).join(","),
        "city": _getCityIds(_selectedCity).join(","),
        "qualification": _selectedQualification.join(","),
        "educationmedium": _selectedEducationMedium.join(","),
        "proffession": _selectedProfession.join(","),
        "workingwith": _selectedWorkingWith.join(","),
        "annualincome": _selectedAnnualIncome.join(","),
        "diet": _selectedDiet.join(","),
        "smokeaccept": _selectedSmokeAcceptance ?? "",
        "drinkaccept": _selectedAlcoholAcceptance ?? "",
        "disabilityaccept": _selectedDisabilityAcceptance ?? "",
        "complexion": _selectedComplexion.join(","),
        "bodytype": _selectedBodyType.join(","),
        "otherexpectation": _otherExpectationsController.text.trim(),
      };

      print("Sending JSON data: $body");

      final response = await http.post(
        Uri.parse("https://digitallami.com/Api2/user_partner.php"),
        body: jsonEncode(body),
        headers: {
          "Content-Type": "application/json; charset=UTF-8",
        },
      ).timeout(const Duration(seconds: 30));

      print("Response status: ${response.statusCode}");
      print("Response body: ${response.body}");

      if (response.statusCode == 200) {
        final result = jsonDecode(response.body);

        if (result["status"] == "success") {
          // Update page number
            _showSuccess("Partner preferences saved successfully!");
            // Navigate after a short delay
Navigator.pop(context);
          } else {
            _showError("Failed to update progress");
          }
        } else {
        final result = jsonDecode(response.body);
          _showError(result["message"] ?? "Unknown error occurred");
        }
      } on FormatException catch (e) {
      print("JSON Format Error: $e");
      _showError("Server response format error. Please try again.");
    } on http.ClientException catch (e) {
      print("Network Error: $e");
      _showError("Network error. Please check your connection.");
    } on TimeoutException catch (e) {
      print("Timeout Error: $e");
      _showError("Request timeout. Please try again.");
    } catch (e) {
      print("Unexpected Error: $e");
      _showError("Something went wrong. Please try again.");
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red,
        duration: const Duration(seconds: 3),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  void _showSuccess(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.green,
        duration: const Duration(seconds: 2),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  @override
  void dispose() {
    _otherExpectationsController.dispose();
    super.dispose();
  }
}